### PR TITLE
Logger is outdated

### PR DESCRIPTION
**Pull request by unasuke**
Use `Itamae.logger` instead of `Logger`.
from itamae v1.5.0

### CODE REVIEW

**Comment by namusyaka** [comment]
Thanks!

**Comment by unasuke** [comment]
@namusyaka plz release new version.(maybe v0.0.2) :pray:

**Comment by namusyaka** [comment]
Just released. Thanks!
https://rubygems.org/gems/itamae-plugin-resource-iptables

**Comment by unasuke** [comment]
Thank you so much!!! :+1:

**Pull request merged**
